#server:
#  servlet:
#    context-path: /api

logging:
  level:
    root: INFO
    cc.ltzent.comiclibrary: DEBUG

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/comic_library_db
    driverClassName: org.postgresql.Driver
    username: spodermon
    password: guesswat
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
            spring:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50000KB
      max-request-size: 50000KB

webapp:
  url: http://localhost:3000


